### ISSUE TITLE
unable to Update All step templates when RunOnServer=true

### ISSUE THREAD

**Issue by MartinDigon** [bluefin-octopusdeploy/chrome-extension#56] opened 2016-05-19 08:10 UTC
Hi,

I incorrectly directed this bug report at Octopus:

Summary: When clicking _Update All_ to update all the projects that use a step template, the updates fail if the projects use the step as _Run on Octopus Server_ without specifying any target roles.

In general it looks like the _Update All_ button doesn't support the _Run on Octopus Server_ that was introduced around Octopus 3.3 (I'm seeing this behaviour in Octopus 3.3.4, Bluefin 1.51.12).

Full details:
http://help.octopusdeploy.com/discussions/problems/45948-unable-to-update-all-step-templates-when-runonservertrue

Thank for the hard work maintaining this extension!

**Comment by davidroberts63** [comment] 2016-05-19 20:11
We will take a look at this. Should be simple to reproduce. In the mean time can you check the JavaScript logs when clicking that button? They will be in the background page for the Bluefin plugin:

1. Manage extensions in Chrome
2. Click the `background page` link for Bluefin. You may have to enable **developer mode** at the top right of the Chrome extensions page to see this.
3. Click on the `Console` tab in the new window.
4. Attempt the update all again for your step template.

You should see a lot of logs show up there. There might be an error one referring to an HTTP 'PUT' operation. The reason I say that is you say you have no target roles. I've accidentally made a step in the past w/o specifying target roles and the update operation not working correctly until I specify at least one role. If you can check that I'll see what I can do about it.

**Comment by davidroberts63** [comment] 2016-05-19 20:13
Oh, well I just read your post on the Octopus support site. Nevermind, you've given me exactly what I need. Awesome bug report Martin!

**Comment by davidroberts63** [comment] 2016-05-22 04:26
@MartinDigon . The problem has been found and working code has been submitted as PR. Should have the fix out for you by sometime Monday (USA).

**Comment by davidroberts63** [comment] 2016-05-23 03:55
Update has been published to Chrome. Should show as available in about an hour. You can also get the release directly from Github.

https://github.com/bluefin-octopusdeploy/chrome-extension/releases/tag/1.51.15

**Closed by davidroberts63** 2016-05-23 03:55 UTC
Labels: bug
